pipeline {
    agent {
    node {
        label 'master'
    }
}
  stages {
    stage('Checkout external proj') {
        steps {
            git branch: 'main',
                credentialsId: 'none',
                url: 'https://github.com/polinushka2/demo.git'

            sh "ls -lat demo"
        }
    }
	stage('Build') { 
            steps {
                def mvnHome= demo
		sh 'chmod +x ${mvnHome}/mvnw; ./${mvnHome}/mvnw package' 
            }
        }	
}
}
