pipeline {
    agent {
    node {
        label 'master'
    }
}
  stages {
    stage('Checkout external proj') {
        steps {
            git branch: 'main',
                credentialsId: 'none',
                url: 'https://github.com/polinushka2/demo.git'

            sh "ls -lat "
        }
    }
	stage('Build') { 
            steps {
		sh 'chmod +x demo/mvnw; cd demo; ./mvnw package' 
            }
        }	
	stage('Test') {
            steps {
                sh 'cd demo; ./mvnw test'
            }
        }
}
}
